# -*- coding: utf-8 -*-
"""task1mark--sparks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZ9zphU-cXR4Ytj0SCUXOxZ3ufHFHV2E

**Importing** **Libraries**
"""

# Commented out IPython magic to ensure Python compatibility.
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt  
# %matplotlib inline

"""**Loading** **Data**"""

data=pd.read_csv('task1.txt')

"""**Splitting into Input and Targets and then Plotting it**"""

X = data.iloc[:, :-1].values  
Y = data.iloc[:, 1].values 
data.plot(x='Hours',y='Scores', style='*')

"""**Training and Predicting**"""

model = LinearRegression()

model.fit(X,Y)

hour=[[9.25]]
pred=model.predict(hour)
print(pred[0])

"""**Training using a train-test Split**"""

from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

model1 = LinearRegression()
model1.fit(X_train, y_train)
ypred=model1.predict(X_test)
print(ypred)

from sklearn import metrics  
print(metrics.mean_absolute_error(y_test, ypred))

result=model1.predict([[9.25]])
print("Predicted Percentage :",result[0])